<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    var BASE_URL = '<?= /* @noEscape */ $block->getUrl('*') ?>';
    var FORM_KEY = '<?= /* @noEscape */ $block->getFormKey() ?>';
    var require = {
        "baseUrl": "<?= /* @noEscape */ $block->getViewFileUrl('/') ?>"
    };
</script>
<div id="ced-message-content" style="display:none">
   <div class="ced-control">
	   <textarea name="comments" value="" maxlength ="2000" title="<?php /* @escapeNotVerified */ //echo __('Detailed Description') ?>" class="input-textarea required-entry" id="ced-messages"></textarea>
	</div>
</div>