<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsVendorReview
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */
/**
 * @var \Magento\Framework\Escaper $escaper
 */
$isAllowed = $block->isAllowed();
$checkVendorProducts = $block->checkVendorProducts();
$displayForm = 0;
?>

<div class="vendor_submit_review_wrap">
    <button type="button" class="ced-submit-review" id="submit-review-button" disabled="true">
        <?= __('Submit your review') ?>
    </button>

    <?php
    if ($isAllowed) {
        if (!$checkVendorProducts) {
            if (!$block->isUserLoggedIn()) { ?>
                <div class="message info notlogged" id="review-form">
                    <div>
                        <?= $escaper->escapeHtml(__('Please login to review product!')) ?>
                    </div>
                </div>
            <?php } else { ?>

                <div class="message info notlogged" id="review-form">
                    <div>
                        <?= $escaper->escapeHtml(
                            __('You cannot review this vendor as you have not purchased any item from this vendor.')
                        )?>
                    </div>
                </div>
            <?php } ?>
        <?php } else {
             if ($block->getAllowWriteReviewFlag()) {
                 if (!$block->getCustomerIsVendor()) {
                        $displayForm = 1;
                 } else { ?>
                    <div class="message info notlogged" id="review-form">
                        <div>
                            <?= $escaper->escapeHtml(__('You can not write review for yourself.')) ?>
                        </div>
                    </div>

                <?php }
            } else { ?>
                <div class="message info notlogged" id="review-form">
                    <div>
                        <?= /* @noEscape */ __('Only registered users can write reviews. Please, <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $this->getLoginLink(),$this->getSignupLink()) ?>
                    </div>
                </div>
            <?php } ?>
        <?php }
    } else { ?>
        <?php if ($block->getAllowWriteReviewFlag()) {
             if (!$block->getCustomerIsVendor()) {
                $displayForm = 1;
                } else { ?>
                <div class="message info notlogged" id="review-form">
                    <div>
                        <?= $escaper->escapeHtml(__('You can not write review for yourself.')) ?>
                    </div>
                </div>

            <?php }
        } else { ?>
            <div class="message info notlogged" id="review-form">
                <div>
                    <?= /* @noEscape */ __('Only registered users can write reviews. Please, <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $this->getLoginLink(),$this->getSignupLink()) ?>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
</div>


<div id="popup-modal" style="display: none">
    <?= $block->getChildHtml('csvendorreview_rating_form'); ?>
</div>
<script type="text/javascript">
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'mage/mage'
        ],
        function(
            $,
            modal
        ) {

            if (window.innerWidth < 767) {
                if ($('.csvendorreview-rating-lists').length) {
                    if (($('.vendor_details').length) && ($('.vendor_submit_review_wrap').length) ) {
                        $('.vendor_submit_review_wrap').insertBefore($('.ced-vendor-view-tabs'))
                    }
                }
            }

            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: false,
                modalClass: 'vendorReviewPopup',
                title: '',
                buttons: []
            };

            var popup = modal(options, $('#popup-modal'));
            $("#submit-review-button").click(function() {
                $('#popup-modal').modal('openModal');
            });
            if (<?= $displayForm ?>) {
                $("#submit-review-button").prop("disabled", false);
            }
        }
    );
</script>
