<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Button
 */
?>
<?= /* @noEscape */ $block->getBeforeHtml(); ?>
<button <?= /* @noEscape */ $block->getAttributesHtml(), $block->getUiId(); ?>>
    <span><?= $block->escapeHtml($block->getLabel()); ?></span>
</button>
<?= /* @noEscape */ $block->getAfterHtml(); ?>
