<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<?php if (!empty($tabs)): ?>
<div id="<?= $block->escapeHtml($block->getId()) ?>">
<ul  class="tabs-horiz">
<?php foreach ($tabs as $_tab): ?>
    <?php $_tabClass = 'tab-item-link ' . $block->getTabClass($_tab) . ' ' . (preg_match('/\s?ajax\s?/', $_tab->getClass()) ? 'notloaded' : '') ?>
    <?php $_tabType = (!preg_match('/\s?ajax\s?/', $_tabClass) && $block->getTabUrl($_tab) != '#') ? 'link' : '' ?>
    <?php $_tabHref = $block->getTabUrl($_tab) == '#' ? '#' . $block->getTabId($_tab) . '_content' : $block->getTabUrl($_tab) ?>
    <li>
        <a href="<?= $block->escapeHtml($_tabHref) ?>" id="<?= $block->escapeHtml($block->getTabId($_tab)) ?>" title="<?= $block->escapeHtml($block->getTabTitle($_tab)) ?>" class="<?php $_tabClass ?>" data-tab-type="<?php $_tabType ?>">
            <span>
                <span class="changed" title="<?= $block->escapeHtml(__('The information in this tab has been changed.')) ?>"></span>
                <span class="error" title="<?= $block->escapeHtml(__('This tab contains invalid data. Please resolve this before saving.')) ?>"></span>
                <span class="loader" title="<?= $block->escapeHtml(__('Loading...')) ?>"></span>
                <?= $block->escapeHtml($block->getTabLabel($_tab)) ?>
            </span>
        </a>
        <div id="<?= $block->escapeHtml($block->getTabId($_tab)) ?>_content" style="display:none"><?= $block->escapeHtml($block->getTabContent($_tab)) ?></div>
    </li>
<?php endforeach; ?>
</ul>
</div>
<script>
require(["jquery","mage/backend/tabs"], function($){
    $(function() {
        $('#<?= $block->escapeHtml($block->getId()) ?>').tabs({
            active: '<?= $block->escapeHtml($block->getActiveTabId()) ?>',
            destination: '#<?= $block->escapeHtml($block->getDestElementId()) ?>',
            shadowTabs: <?= $block->escapeHtml($block->getAllShadowTabs()) ?>
        });
    });
});
</script>
<?php endif; ?>
