<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="admin__data-grid-export">
    <label for="<?= /* @noEscape */ $block->getId() ?>_export" class="admin__control-support-text">
        <?= /* @noEscape */ __('Export to:') ?>
    </label>
    <select name="<?= /* @noEscape */ $block->getId() ?>_export" id="<?= /* @noEscape */ $block->getId() ?>_export" class="admin__control-select">
        <?php foreach ($block->getExportTypes() as $_type): ?>
            <option value="<?= /* @noEscape */ $_type->getUrl() ?>"><?= /* @noEscape */ $_type->getLabel() ?></option>
        <?php endforeach; ?>
    </select>
    <?= /* @noEscape */ $block->getExportButtonHtml() ?>
</div>