<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsVendorReview
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

?>
<?php
$width = $block->getVendorRating();
$helper = $block->helper();
if ($width > 1 && $helper->isReviewAllowed()) { ?>
    <div class="vendor-rating">
        <div class="rating-summary">
            <div title="<?= $escaper->escapeHtml($width) ?>%" class="rating-result">
                <span style="width:<?= $escaper->escapeHtml($width) ?>%;">
                    <span><?= $escaper->escapeHtml($width) ?>%</span>
                </span>
            </div>
        </div>
    </div>
<style>
    .vendor-rating {
       float: right;
    }
</style>
<?php } ?>